apiVersion: v1
kind: Secret
metadata:
  name: {{ include "connectwell.fullname" . | default (printf "%s" .Chart.Name) }}-secret
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "{{ .Values.secrets.django_secret_key }}"
  YOCO_WEBHOOK_SECRET: "{{ .Values.secrets.yoco_webhook_secret }}"
  # You should override these values in production using kubectl create secret or Helm --set-file
