[mypy]
ignore_missing_imports = True
exclude = (?x)
    (^|/)_?venv/|
    (^|/)backend/.venv/|
    /migrations/

# Suppress a small number of attribute/type issues in settings used at runtime
per-module-ignores =
    connectwell.settings: attr-defined
