# Generated by Django 5.2.8 on 2025-11-16 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '__first__'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchsession',
            name='user_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_a', to='accounts.user'),
        ),
        migrations.AddField(
            model_name='matchsession',
            name='user_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_b', to='accounts.user'),
        ),
    ]
