# Generated by Django 5.2.8 on 2025-11-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_matchsession_user_a_matchsession_user_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchsession',
            name='unblur_price',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='matchsession',
            name='user_a_unblurred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchsession',
            name='user_b_unblurred',
            field=models.BooleanField(default=False),
        ),
    ]
